version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_DATABASE: hallate_hallate
      DB_USERNAME: hallate_hallate
      DB_PASSWORD: 20lemuluKO
      DB_PORT: 3306
    networks:
      - laravel
    volumes:
      - /Users/santiagovargas/Documents/Proyectos/laravel9/my-site/hallate-web:/var/www/html

  db:
    image: mysql
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: hallate_hallate
      MYSQL_USER: hallate_hallate
      MYSQL_PASSWORD: 20lemuluKO
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8000:80"
    environment:
      PMA_ARBITRARY: 1
    networks:
      - laravel
    depends_on:
      - db

volumes:
  mysql-data:
    driver: local

networks:
  laravel:
